### ISSUE TITLE
Cannot install on Windows or Linux

### ISSUE THREAD

**Issue by daknoll** [tillahoffmann/asymmetric_kde#12]
`pip install git+https://github.com/tillahoffmann/asymmetric_kde` appears to succeed on Windows and Linux.  The command creates an `asymmetric_kde-1.0.dist-info/` directory but does not create an `asymmetric_kde/` directory.

**Comment by daknoll** [comment]
Till, 

Thank you for your quick fix to the asymmetric_kde project!  I am now able to install version 1.1 on Linux (Google Colab) and Windows.

I still have some problems importing your package however.  On Google Colab "from asymmetric_kde import *" does not work but "from asymmetric_kde.asymmetric_kde import *" does work.  On Windows neither of those work.  This may reflect my unfamiliarity with Python's import system rather than any problems with your package.

At the very least I am able to run your code by directly including it in my project.  Do you have any particular license restrictions?

Thank you!

**Comment by tillahoffmann** [comment]
Indeed, there was a pesky little period missing (see #14). I've also added an Apache license.

**Comment by daknoll** [comment]
Tested on Linux and Windows and works great!  Thanks for all your efforts!
